-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('ADMIN', 'CUSTOMER', 'ORGANIZER') NULL,
    MODIFY `referralCode` VARCHAR(191) NULL,
    MODIFY `points` INTEGER NULL DEFAULT 0,
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
